//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LosInges.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restauracion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Restauracion()
        {
            this.Factura = new HashSet<Factura>();
            this.Auto1 = new HashSet<Auto>();
            this.Producto1 = new HashSet<Producto>();
        }
    
        public int IdRestauracion { get; set; }
        public Nullable<int> IdAuto { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public Nullable<int> IdDepartamento { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> PrecioRestauracion { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public Nullable<System.DateTime> FechaReatauracion { get; set; }
    
        public virtual Auto Auto { get; set; }
        public virtual Departamento Departamento { get; set; }
        public virtual Empleado Empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factura> Factura { get; set; }
        public virtual Producto Producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Auto> Auto1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Producto> Producto1 { get; set; }
    }
}
